apiVersion: v1
kind: Service
metadata:
  name: insecure-demo-app
  namespace: runtime-demo
  labels:
    app: insecure-demo-app
spec:
  type: ClusterIP
  selector:
    app: insecure-demo-app
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
